#!/usr/bin/fish

set cached_pwd $pwd
sudo pacman -S base-devel

cd ~/pawsoff/pkgs
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
cd ..

set packages \
	brightnessctl \
	fastfetch \
	fish \
	fuzzel \
	ghostty \
	grim \
	luarocks \
	man-db \
	man-pages \
	meson \
	neovim \
	noto-fonts-emoji \
	phinger-cursors \
	plymouth \
	pw-volume \
	river-classic \
	sddm \
	slurp \
	spicetify-cli \
	spotify \
	swww \
	ttf-noto-sans-cjk-vf \
	ungoogled-chromium-bin \
	waybar \
	ytdl \
	zip

yay -S $packages
cd $cached_pwd
