#!/usr/bin/fish

set mod Super
set left h
set right l
set up k
set down j

riverctl map normal $mod+Shift R spawn ~/pawsoff/dots/river/rc
riverctl map normal $mod+Shift Q exit

riverctl map normal $mod Q close
riverctl map normal $mod Return spawn fuzzel

riverctl map normal $mod+Shift $left swap left
riverctl map normal $mod+Shift $right swap right
riverctl map normal $mod+Shift $up swap up
riverctl map normal $mod+Shift $down swap down

riverctl map normal $mod $left focus-view left
riverctl map normal $mod $right focus-view right
riverctl map normal $mod $up focus-view up
riverctl map normal $mod $down focus-view down

for tag in ( seq 1 4 )
	riverctl map normal $mod $tag set-focused-tags ( math "2^( $tag - 1 )" )
end

riverctl focus-follows-cursor enabled
riverctl xcursor-theme phinger-cursors-light 48

riverctl background-color 0xffffff
riverctl border-color 0x000000
riverctl border-width 4

if ! pgrep rivertile
	riverctl default-layout rivertile
	rivertile -outer-padding 4 -view-padding 4 &
end

if ! pgrep swww-daemon
	swww-daemon &
	swww img ~/pawsoff/resources/wallpapers/Kiki\ Cat
end

if ! pgrep waybar
	waybar &
else
	pkill -USR2 waybar
end
