#!/usr/bin/fish

set mod Mod4
set left h
set right l
set up k
set down j

set term ghostty

riverctl map normal $mod R spawn ~/pawsoff/config/river/rc
riverctl map normal $mod Q exit

riverctl map normal $mod Return spawn $term

riverctl map normal $mod+Shift $left swap left
riverctl map normal $mod+Shift $right swap right
riverctl map normal $mod+Shift $up swap up
riverctl map normal $mod+Shift $down swap down

riverctl map normal $mod $left focus-view left
riverctl map normal $mod $right focus-view right
riverctl map normal $mod $up focus-view up
riverctl map normal $mod $down focus-view down

riverctl focus-follows-cursor disabled

riverctl background-color 0x101017

riverctl border-color-focused 0xe0e0e0
riverctl border-color-unfocused 0x404040
riverctl border-width 4

if ! pgrep rivertile
	riverctl default-layout rivertile
	rivertile -outer-padding 8 -view-padding 8 &
end

if ! pgrep swww-daemon
	swww-daemon &
	swww img ~/pawsoff/share/wallpapers/Kiki\ Town
end

if ! pgrep waybar
	waybar &
else
	pkill -USR2 waybar
end
