#!/usr/bin/fish

argparse "s/save" "S/saveas" "r/region" -- $argv
mkdir -p ~/pawsoff/misc/screenshots &> /dev/null

set data
if test $_flag_region
	set data $(grim -g $(slurp) -)
else
	set data $(grim -)
end

set file
if test $_flag_save
	set file $(date +"%Y.%m.%d %T")
	echo $data > ~/pawsoff/misc/screenshots/$file
else if test $_flag_saveas
	set file $(fuzzel -c ~/pawsoff/dots/grim/menu -- )
	echo $data > ~/pawsoff/misc/screenshots/$file
end

wl-copy $data
